appName: webapp
image:
  name: eyesoncloud/webapp
  tag: 34

replicaCount: 2
configmap:
   name: webapp
   data:
     CUSTOM_HEADER: "welcome to React app"

service:
  type: ClusterIP
  port: 3000

route:
  enabled: true
  host: reactapp.example.com

rbac:
  enabled: true

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

#namespace: react-app
