apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-react-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-react-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-react-app
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: react-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
