apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-react-app-route
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-react-app
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}-react-app-service
  host: {{ .Values.route.host }}
  port:
    targetPort: 3000
