apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-route
  #namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}-service
  host: {{ .Values.route.host }}
  port:
    targetPort: 3000